# Generated by Django 4.2.3 on 2023-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_keywords', models.TextField(max_length=100)),
                ('display_keywords', models.TextField(max_length=100)),
            ],
        ),
    ]
