# Generated by Django 4.2.3 on 2023-08-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcreatorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='display_keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='pic_keywords',
            field=models.TextField(),
        ),
    ]
