# Generated by Django 4.2.3 on 2023-08-31 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcreatorApp', '0002_alter_keywords_display_keywords_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='keywords',
            new_name='keyword',
        ),
    ]
