# Generated by Django 4.2.3 on 2023-09-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcreatorApp', '0003_rename_keywords_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='id',
        ),
        migrations.AddField(
            model_name='keyword',
            name='keyword_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='display_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='pic_keywords',
            field=models.TextField(default=''),
        ),
    ]
