# Generated by Django 4.2.3 on 2023-09-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcreatorApp', '0005_rename_keyword_id_keyword_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
