# Generated by Django 4.2.3 on 2023-09-03 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcreatorApp', '0006_alter_keyword_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgpaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(default='')),
                ('fk_pkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcreatorApp.keyword')),
            ],
        ),
    ]
