# Generated by Django 4.2.3 on 2023-09-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcreatorApp', '0007_imgpaths'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imgpaths',
            new_name='Imgpath',
        ),
    ]
