# Generated by Django 4.2.5 on 2023-09-07 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcreatorApp', '0009_delete_imgpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgpath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paths', models.TextField(default='')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcreatorApp.keyword')),
            ],
        ),
    ]
