# Generated by Django 4.2.5 on 2023-09-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcreatorApp', '0010_imgpath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgpath',
            old_name='keyword',
            new_name='fk',
        ),
    ]
